# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Robert\repos\Electronic\stateChangeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_increaseReduce(object):
    def setupUi(self, increaseReduce):
        increaseReduce.setObjectName("increaseReduce")
        increaseReduce.resize(400, 117)
        self.buttonBox = QtWidgets.QDialogButtonBox(increaseReduce)
        self.buttonBox.setGeometry(QtCore.QRect(220, 90, 166, 21))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.spinBox = QtWidgets.QSpinBox(increaseReduce)
        self.spinBox.setGeometry(QtCore.QRect(130, 40, 251, 22))
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(increaseReduce)
        self.label.setGeometry(QtCore.QRect(20, 30, 101, 41))
        self.label.setObjectName("label")

        self.retranslateUi(increaseReduce)
        self.buttonBox.clicked['QAbstractButton*'].connect(self.spinBox.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(increaseReduce)

    def retranslateUi(self, increaseReduce):
        _translate = QtCore.QCoreApplication.translate
        increaseReduce.setWindowTitle(_translate("increaseReduce", "Form"))
        self.label.setText(_translate("increaseReduce", "TextLabel"))
